export const FETCH_TODO_LIST = 'FETCH_TODO_LIST';
export const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';
export const CREATE_NEW_TODO = 'CREATE_NEW_TODO';
export const FETCH_TODO_BY_ID = 'FETCH_TODO_BY_ID';
export const UPDATE_TODO_BY_ID = 'UPDATE_TODO_BY_ID';